on:
  push:
    branches:
    - main
    - dev
    - old

jobs:
  run_linguist:
    name: Run github-linguist on the repo
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd $GITHUB_WORKSPACE
          github-linguist
