on:
  push:
    branches:
    - main
    - dev
    - old

jobs:
  run_linguist:
    name: Run github-linguist on the repo
    runs-on: macos-latest
    steps:
      - run: |
          sudo gem install github-linguist
          github-linguist
