on:
  push:
    branches:
    - main

jobs:
  run_tectonic:
    name: Run tectonic on the repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install Tectonic
        run: |
          sudo apt install curl
          curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net | sh

      - name: Compile the template
        run: |
          ./tectonic "NoTeX Documentation.tex" -Z continue-on-errors --color=always

