on:
  push:
    branches:
    - main
    - dev
    - old

jobs:
  run_linguist:
    name: Run github-linguist on the repo
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd $GITHUB_WORKSPACE
          cd ../
          git status
          #sudo apt-get install build-essential cmake pkg-config libicu-dev zlib1g-dev libcurl4-openssl-dev libssl-dev ruby-dev
          #sudo gem install github-linguist
          #github-linguist
